version: '3.8'

services:
  db:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: todo_database
    networks:
      - django-network
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD']
      interval: 10s
      timeout: 2s
      retries: 100

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_HOST: db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - django-network

networks:
  django-network:

volumes:
  mysql-data: